### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by CaptInsano** [swinbkh/WLED_WT32_Board#1]
Not an issue but I knew of no other way to contact you to say thanks!

I am subscribed to the WLED Ethernet Support issue: https://github.com/Aircoookie/WLED/issues/1027 and saw your link to these gerber files. 
I have received my PCBS and parts and have them now running in my house.

Thanks so much for your work!

Ignore the longer than required header sockets (they were what I had in "stock")

![PXL_20210308_162633500](https://user-images.githubusercontent.com/332478/110350461-a67b9c80-802b-11eb-843a-643724274a6a.jpg)

After assembling 2 of them I realized that there was enough room to have the terminals installed on the bottom of the board making it a little more streamlined for inserting into a 3D printed case in the future:

![PXL_20210308_162653331](https://user-images.githubusercontent.com/332478/110350635-d4f97780-802b-11eb-8df6-e1cd7f36880a.jpg)

Thanks again.

**Comment by swinbkh** [comment]
@CaptInsano Awesome job! I love the idea of mounting the screw terminals upside down, so long as you can still seperate the boards to tighten up the screws. I'm glad you got on okay with it - makes me glad I shared it with the community :)

**Comment by CaptInsano** [comment]
> @CaptInsano Awesome job! I love the idea of mounting the screw terminals upside down, so long as you can still seperate the boards to tighten up the screws.

The boards separate easily and is very low profile when re-assembled.


> @CaptInsano makes me glad I shared it with the community :)

That is why I wanted to take the time to thank you!
